### ISSUE TITLE
NPE when creating STUB with no headers section defined

### ISSUE THREAD

**Issue by szymon-owczarzak** [wttech/aem-stubs#52]
https://github.com/wttech/aem-stubs/blob/d1935aa4c431d31769f532d3f949739c07c55340/wiremock/src/main/java/com/cognifide/aem/stubs/wiremock/transformers/PebbleTransformer.java#L97

Wiremock does not require the `headers` section for the request/response sections. Please consider some reasonable defaults when  header section is not present.

```json
{
  "mappings": [
    {
      "request": {
        "method": "GET",
        "url": "/my-document-pdf"
      },
      "response": {
        "status": 200,
        "bodyFileName": "documents/my.pdf"
      }
    }
  ]
}
```

```
java.lang.NullPointerException: null
	at com.cognifide.aem.stubs.wiremock.transformers.PebbleTransformer.hasTextMimeType(PebbleTransformer.java:97) [com.cognifide.aem.stubs.wiremock:2.0.1]
	at com.cognifide.aem.stubs.wiremock.transformers.PebbleTransformer.lambda$transformBody$3(PebbleTransformer.java:88) [com.cognifide.aem.stubs.wiremock:2.0.1]
	at java.util.Optional.map(Optional.java:215)
```

**Comment by pun-ky** [comment]
@marcinkp hardening needed :)

**Comment by pun-ky** [comment]
IMO pebble templating is introducing many incompatibilities and I am quite sure that supporting it should be dropped

**Comment by krystian-panek-vmltech** [comment]
no longer valid for v4
